# Generated by Django 5.2.9 on 2026-01-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_alter_thought_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="Default.png", null=True, upload_to="media/"
            ),
        ),
    ]
